version: "3"

services:
  web-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "django-web"
    volumes:
      - .:/code
      - /code/.idea/
      - /code/.vscode/
      - /code/venv/
    ports:
      - "8000:8000"