version: "3"

services:
  web-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ResearchRealm"
    volumes:
      - .:/code
      - /code/.idea/
      - /code/.vscode/
      - /code/venv/
    ports:
      - "8005:8005"