# Generated by Django 5.0.3 on 2024-03-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarStack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='user',
            new_name='author',
        ),
    ]
