# Generated by Django 5.0.3 on 2024-03-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarStack', '0002_rename_user_thesis_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='author',
            new_name='user',
        ),
    ]
