# Generated by Django 5.0.3 on 2024-03-25 02:36

import ScholarStack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarStack', '0003_rename_author_thesis_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='url',
        ),
        migrations.AlterField(
            model_name='thesis',
            name='content',
            field=models.FileField(db_column='author', unique=True, upload_to=ScholarStack.models.user_directory_path),
        ),
    ]
