# Generated by Django 5.0.3 on 2024-03-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarStack', '0006_alter_thesis_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='last_ip',
        ),
    ]
